"""initial_schema

Revision ID: 11b2d5cade18
Revises: 
Create Date: 2026-05-12 22:07:08.321613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11b2d5cade18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buy_id'), 'buy', ['id'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('figi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('figi')
    )
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.create_index(op.f('ix_instruments_ticker'), 'instruments', ['ticker'], unique=True)
    op.create_table('investment_plan_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('amount_rub', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('execution_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_plan_executions_created_at'), 'investment_plan_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_investment_plan_executions_id'), 'investment_plan_executions', ['id'], unique=False)
    op.create_index(op.f('ix_investment_plan_executions_plan_id'), 'investment_plan_executions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_investment_plan_executions_status'), 'investment_plan_executions', ['status'], unique=False)
    op.create_index(op.f('ix_investment_plan_executions_ticker'), 'investment_plan_executions', ['ticker'], unique=False)
    op.create_table('investment_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('lots', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('price_rule', sa.String(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('confirmation_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_plans_id'), 'investment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_investment_plans_ticker'), 'investment_plans', ['ticker'], unique=False)
    op.create_table('margin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_margin_id'), 'margin', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('signal', sa.String(), nullable=True),
    sa.Column('bm_value', sa.Float(), nullable=True),
    sa.Column('operation_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('research_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('source_names', sa.Text(), nullable=True),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('data_gap_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_snapshots_created_at'), 'research_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_snapshots_generated_at'), 'research_snapshots', ['generated_at'], unique=False)
    op.create_index(op.f('ix_research_snapshots_id'), 'research_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_research_snapshots_ticker'), 'research_snapshots', ['ticker'], unique=False)
    op.create_table('scheduler_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collapse_updates', sa.Boolean(), nullable=True),
    sa.Column('collapse_updates_time', sa.String(), nullable=True),
    sa.Column('market_updates', sa.Boolean(), nullable=True),
    sa.Column('market_updates_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduler_config_id'), 'scheduler_config', ['id'], unique=False)
    op.create_table('signal_alligator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jaw_period', sa.Integer(), nullable=True),
    sa.Column('jaw_shift', sa.Integer(), nullable=True),
    sa.Column('teeth_period', sa.Integer(), nullable=True),
    sa.Column('teeth_shift', sa.Integer(), nullable=True),
    sa.Column('lips_period', sa.Integer(), nullable=True),
    sa.Column('lips_shift', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_alligator_id'), 'signal_alligator', ['id'], unique=False)
    op.create_table('signal_bollinger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('deviation', sa.Float(), nullable=True),
    sa.Column('type_ma', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_bollinger_id'), 'signal_bollinger', ['id'], unique=False)
    op.create_table('signal_ema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fastLength', sa.Integer(), nullable=True),
    sa.Column('slowLength', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_ema_id'), 'signal_ema', ['id'], unique=False)
    op.create_table('signal_gpt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_gpt_id'), 'signal_gpt', ['id'], unique=False)
    op.create_table('signal_macd',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fastLength', sa.Integer(), nullable=True),
    sa.Column('slowLength', sa.Integer(), nullable=True),
    sa.Column('signalLength', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_macd_id'), 'signal_macd', ['id'], unique=False)
    op.create_table('signal_rsi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Float(), nullable=True),
    sa.Column('hightLevel', sa.Float(), nullable=True),
    sa.Column('lowLevel', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_rsi_id'), 'signal_rsi', ['id'], unique=False)
    op.create_table('signal_sma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fastLength', sa.Integer(), nullable=True),
    sa.Column('slowLength', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_sma_id'), 'signal_sma', ['id'], unique=False)
    op.create_table('signal_tpsl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_tpsl_id'), 'signal_tpsl', ['id'], unique=False)
    op.create_table('strategy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('auto_market', sa.Boolean(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('joint', sa.Boolean(), nullable=True),
    sa.Column('sandbox_trigger', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_settings_id'), 'strategy_settings', ['id'], unique=False)
    op.create_table('strategy_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tpls_trigger', sa.Boolean(), nullable=True),
    sa.Column('rsi_trigger', sa.Boolean(), nullable=True),
    sa.Column('sma_trigger', sa.Boolean(), nullable=True),
    sa.Column('ema_trigger', sa.Boolean(), nullable=True),
    sa.Column('alligator_trigger', sa.Boolean(), nullable=True),
    sa.Column('gpt_trigger', sa.Boolean(), nullable=True),
    sa.Column('lstm_trigger', sa.Boolean(), nullable=True),
    sa.Column('bollinger_trigger', sa.Boolean(), nullable=True),
    sa.Column('macd_trigger', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_signals_id'), 'strategy_signals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_strategy_signals_id'), table_name='strategy_signals')
    op.drop_table('strategy_signals')
    op.drop_index(op.f('ix_strategy_settings_id'), table_name='strategy_settings')
    op.drop_table('strategy_settings')
    op.drop_index(op.f('ix_signal_tpsl_id'), table_name='signal_tpsl')
    op.drop_table('signal_tpsl')
    op.drop_index(op.f('ix_signal_sma_id'), table_name='signal_sma')
    op.drop_table('signal_sma')
    op.drop_index(op.f('ix_signal_rsi_id'), table_name='signal_rsi')
    op.drop_table('signal_rsi')
    op.drop_index(op.f('ix_signal_macd_id'), table_name='signal_macd')
    op.drop_table('signal_macd')
    op.drop_index(op.f('ix_signal_gpt_id'), table_name='signal_gpt')
    op.drop_table('signal_gpt')
    op.drop_index(op.f('ix_signal_ema_id'), table_name='signal_ema')
    op.drop_table('signal_ema')
    op.drop_index(op.f('ix_signal_bollinger_id'), table_name='signal_bollinger')
    op.drop_table('signal_bollinger')
    op.drop_index(op.f('ix_signal_alligator_id'), table_name='signal_alligator')
    op.drop_table('signal_alligator')
    op.drop_index(op.f('ix_scheduler_config_id'), table_name='scheduler_config')
    op.drop_table('scheduler_config')
    op.drop_index(op.f('ix_research_snapshots_ticker'), table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_id'), table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_generated_at'), table_name='research_snapshots')
    op.drop_index(op.f('ix_research_snapshots_created_at'), table_name='research_snapshots')
    op.drop_table('research_snapshots')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_margin_id'), table_name='margin')
    op.drop_table('margin')
    op.drop_index(op.f('ix_investment_plans_ticker'), table_name='investment_plans')
    op.drop_index(op.f('ix_investment_plans_id'), table_name='investment_plans')
    op.drop_table('investment_plans')
    op.drop_index(op.f('ix_investment_plan_executions_ticker'), table_name='investment_plan_executions')
    op.drop_index(op.f('ix_investment_plan_executions_status'), table_name='investment_plan_executions')
    op.drop_index(op.f('ix_investment_plan_executions_plan_id'), table_name='investment_plan_executions')
    op.drop_index(op.f('ix_investment_plan_executions_id'), table_name='investment_plan_executions')
    op.drop_index(op.f('ix_investment_plan_executions_created_at'), table_name='investment_plan_executions')
    op.drop_table('investment_plan_executions')
    op.drop_index(op.f('ix_instruments_ticker'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_buy_id'), table_name='buy')
    op.drop_table('buy')
    # ### end Alembic commands ###
