"""add_auto_schedule_fields

Revision ID: 25c070e207b5
Revises: 677b093fb5a9
Create Date: 2026-05-13 00:16:16.791426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c070e207b5'
down_revision: Union[str, Sequence[str], None] = '677b093fb5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_plan_executions', sa.Column('skipped_reason', sa.String(), nullable=True))
    op.add_column(
        'investment_plans',
        sa.Column('operation', sa.String(), server_default='buy', nullable=False),
    )
    op.add_column('investment_plans', sa.Column('price_limit', sa.Float(), nullable=True))
    op.add_column('investment_plans', sa.Column('pct_threshold', sa.Float(), nullable=True))
    op.add_column('investment_plans', sa.Column('avg_period_days', sa.Integer(), nullable=True))
    op.add_column(
        'investment_plans',
        sa.Column('confirmation_mode', sa.String(), server_default='telegram_confirm', nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_plans', 'confirmation_mode')
    op.drop_column('investment_plans', 'avg_period_days')
    op.drop_column('investment_plans', 'pct_threshold')
    op.drop_column('investment_plans', 'price_limit')
    op.drop_column('investment_plans', 'operation')
    op.drop_column('investment_plan_executions', 'skipped_reason')
    # ### end Alembic commands ###
